version: '3.8'

services:
  # sqlitebrowser:
  #   image: lscr.io/linuxserver/sqlitebrowser:latest
  #   container_name: sqlitebrowser
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ./data:/config  # Mount your SQLite database directory
  #   ports:
  #     - "3000:3000"  # Web UI
  #   restart: unless-stopped

  # webstash:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   environment:
  #     - ENV=development

  users:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "0:8080"
    volumes: 
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=development
      - SERVICE=users

postgres:
    image: postgres:16 # Use the desired PostgreSQL version
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for Postgres

  redis:
    image: redis:7 # Use the desired Redis version
    container_name: redis-server
    command: ["redis-server", "--appendonly", "yes"] # Enable AOF persistence
    ports:
      - "6379:6379" # Expose Redis on port 6379
    volumes:
      - redis_data:/data # Persistent storage for Redis

volumes:
  postgres_data: # Volume for PostgreSQL data
  redis_data: # Volume for Redis data
  
